# Generated by Django 3.1.3 on 2020-12-03 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Категория номера')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Updated')),
                ('number', models.PositiveSmallIntegerField(verbose_name='№ Номера')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Взрослых')),
                ('facilities', models.CharField(max_length=255, verbose_name='Оснащение номера')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Площадь, м2')),
                ('bad_type', models.CharField(default='Двух местная', max_length=255, verbose_name='Тип кровати')),
                ('description', models.TextField(max_length=2500, verbose_name='Описание номера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.category', verbose_name='Категория номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номерa',
            },
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Updated')),
                ('image', models.ImageField(blank=True, upload_to='rooms', verbose_name='Фото номера')),
                ('sorting', models.PositiveSmallIntegerField(blank=True, help_text='Сортировка по увеличению, начиная с 1. Фотография с наименьшим значением сортировки будет основной', verbose_name='Сортировка фотографий')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Галерея фото')),
            ],
            options={
                'verbose_name': 'Фотография номера',
                'verbose_name_plural': 'Фотографии номеров',
                'ordering': ['sorting'],
            },
        ),
    ]
