# Generated by Django 3.1.3 on 2020-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201203_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomgallery',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room', verbose_name='Галерея фото'),
        ),
    ]
