# Generated by Django 3.1.3 on 2020-12-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201204_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomgallery',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Галерея фото'),
        ),
    ]
