# Generated by Django 3.1.3 on 2020-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201204_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomgallery',
            name='sorting',
            field=models.PositiveSmallIntegerField(help_text='Сортировка по увеличению, начиная с 1. Фотография с наименьшим значением сортировки будет основной', verbose_name='Сортировка фотографий'),
        ),
    ]
