# Generated by Django 3.1.3 on 2020-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201204_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Опция цены')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rooms.priceoptions', verbose_name='Цена номера'),
            preserve_default=False,
        ),
    ]
