# Generated by Django 3.1.3 on 2020-12-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201204_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceoptions',
            options={'verbose_name': 'Опции цены', 'verbose_name_plural': 'Опции цен'},
        ),
    ]
