# Generated by Django 3.1.3 on 2020-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20201204_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Все номерa'},
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена номера'),
        ),
        migrations.DeleteModel(
            name='PriceOptions',
        ),
    ]
